services:
  unpackerr:
    image: golift/unpackerr
    container_name: Unpackerr
    volumes:
      # You need at least this one volume mapped so Unapckerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - PATHTOFILES:/Media #EDIT THIS - UPDATE FOR MORE INFO LATER
    restart: unless-stopped
    # Get the user:group correct so unpackerr can read and write to your files.
    user: USERIDHERE:GROUPIDHERE #EDIT THIS
    #user: 1001:1001
    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    environment:
      - TZ=America/Chicago
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://Sonarr:PORTFROMAPP #EDIT THIS
      - UN_SONARR_0_API_KEY=YOURSONARRAPIKEY #EDIT THIS
      - UN_SONARR_0_PATHS_0=/YOURTORRENTPATH #EDIT THIS
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=20s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://Radarr:PORTFROMAPP #EDIT THIS
      - UN_RADARR_0_API_KEY=YOURRADARRAPIKEY #EDIT THIS
      - UN_RADARR_0_PATHS_0=/YOURTORRENTPATH #EDIT THIS
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=20s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Folder Config
      - UN_FOLDER_0_PATH=
      - UN_FOLDER_0_EXTRACT_PATH=
      - UN_FOLDER_0_DELETE_AFTER=10m
      - UN_FOLDER_0_DELETE_ORIGINAL=false
      - UN_FOLDER_0_DELETE_FILES=false
      - UN_FOLDER_0_MOVE_BACK=false
      # Webhook Config
#      - UN_WEBHOOK_0_URL=
#      - UN_WEBHOOK_0_NAME=
#      - UN_WEBHOOK_0_NICKNAME=Unpackerr
#      - UN_WEBHOOK_0_CHANNEL=
#      - UN_WEBHOOK_0_TIMEOUT=10s
#      - UN_WEBHOOK_0_SILENT=false
#      - UN_WEBHOOK_0_IGNORE_SSL=false
#      - UN_WEBHOOK_0_EXCLUDE_0=
#      - UN_WEBHOOK_0_EVENTS_0=0
#      - UN_WEBHOOK_0_TEMPLATE_PATH=
#      - UN_WEBHOOK_0_CONTENT_TYPE=application/json
    security_opt:
      - no-new-privileges:true